#!/bin/sh
# Background-Resizer
# Copyright (c) 2021, chris1111. All Right Reserved
# Credit: Apple Image Processing System (sips)
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# Vars

for var in "$@"
do
    echo "Resizing $var"
    basename=$(echo "$var" | cut -f 1 -d '.')
    sips -z 2160 3840 "$var" --out "$basename-3840x2160.png" &> /dev/null
    sips -z 2880 5120 "$var" --out "$basename-5120x2880.png" &> /dev/null
    sips -z 1600 2560 "$var" --out "$basename-2560x1600.png" &> /dev/null
    sips -z 2400 3840 "$var" --out "$basename-3840x2400.png" &> /dev/null
    sips -z 2100 3360 "$var" --out "$basename-3360x2100.png" &> /dev/null
    sips -z 2400 3200 "$var" --out "$basename-3200x2400.png" &> /dev/null
    sips -z 1800 3200 "$var" --out "$basename-3200x1800.png" &> /dev/null
    sips -z 2160 2880 "$var" --out "$basename-2880x2160.png" &> /dev/null
    sips -z 1536 2732 "$var" --out "$basename-2732x1536.png" &> /dev/null
    sips -z 1800 2880 "$var" --out "$basename-2880x1800.png" &> /dev/null
    sips -z 1536 2048 "$var" --out "$basename-2048x1536.png" &> /dev/null
done

if [ ! $# -eq "0" ]; then
osascript <<EOD
  tell application "Background-Resizer"
      activate
  end tell
EOD

    echo "Done processing $# images"
else
    echo "Welcome Background-Resizer

Drop your Background images to resize them, only PNG and JPG images are accept the Background must be in 1920x1080, an unlimited number of images can be dropped.
The images will be resize to:

3840x2160.png-5120x2880.png-2560x1600.png-3840x2400.png-3360x2100.png-3200x2400.png-3200x1800.png-2880x2160.png-2880x1800.png-2732x1536.png-2880x1800.png-2048x1536.png 
🔍 ➤ in the same directory as your original image."
fi
